name: dotnet-package-docker

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    # 使用官方 dotnet SDK 9.0 的 Docker 映像檔
    container:
      image: mcr.microsoft.com/dotnet/sdk:9.0

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build --no-restore

      - name: Run tests
        run: dotnet test --no-build --logger trx --results-directory TestResults

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: test-results
          path: TestResults
